### PR TITLE
Dev/fix some convert function

### PR DESCRIPTION
**Pull request by 2bbb**

### CODE REVIEW

**Comment by hideakitai** [comment]
line 66 and 73 makes invalid type error... 
maybe ```same_size_int_t<unsigned int(1, 2, 4, 8)>``` makes such errors.
can you fix that?
```
myUnion.x = toIntegral<same_size_int_t<float>>(floatHexString);
```

**Comment by 2bbb** [comment]
omg.
fixed.

**Comment by hideakitai** [comment]
mmm... still there is compile errors (also in ```same_size_int_t<double>```)
```
EmbeddedUtils/lib/Convert.h:66:48: error: type/value mismatch at argument 1 in template parameter list for 'template<unsigned int size> using same_size_int_t = typename Convert::same_size_int::type'
myUnion.x = toIntegral<same_size_int_t<float>>(floatHexString);
^
EmbeddedUtils/lib/Convert.h:66:48: error:   expected a constant of type 'unsigned int', got 'float'
EmbeddedUtils/lib/Convert.h:66:70: error: no matching function for call to 'toIntegral(const String&)'
myUnion.x = toIntegral<same_size_int_t<float>>(floatHexString);
```

**Comment by 2bbb** [comment]
do?

**Comment by hideakitai** [comment]
yeah, great. thank you for the cool support!

**Pull request merged**
